# Header

menu:
  主页: /
  所有文章: /archives
  随笔: /tag/随笔/
  关于我: /about

# SubNav
subnav:
  github: "https://ithack.github.io"
  weibo: "http://weibo.com/271855993?is_all=1"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/yy-yy-98"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  #mail: "mailto:litten225@qq.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/bragonro"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: false

# Content

# 文章太长，截断按钮文字
excerpt_link: more
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: true

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '有钱没钱捧个场'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /images/ipay/ap.jpg
# 微信二维码图片地址
weixin: /images/ipay/wx.jpg



# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: false
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: 'f30522fc4518f6f15df432c53d9c258d'
google_analytics: 'UA-39380047-2'
favicon: /images/个人信息/favicon.ico

#开启百度统计
baidu_tongji: true

#你的头像url
avatar: "/images/个人信息/my_proto.jpg"

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
#gitment_owner: 'ithack'      #你的 GitHub ID
#gitment_repo: 'myGitment'          #存储评论的 repo
#gitment_oauth:
#  client_id: '90e5e544e45855945cc8'           #client ID
#  client_secret: '1373c1cefa6c3dd3af20366caae500e8962b3191'       #client secret

#6、Valine https://valine.js.org
valine:
 #leancloud: http://pirogue.org/js/av-min.js
 appid: 'muiRoOrtUHprjUm08CdarBGI-gzGzoHsz' #Leancloud应用的appId
 appkey: 'eQEhP9kqkEsV1WcX5GQDfhT3' #Leancloud应用的appKey
 verify: false #验证码
 notify: false #评论回复提醒
 visitor: true #文章访问量
 avatar: mp #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
 placeholder: Just go go #评论框占位符

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  # friends: '友链'
  aboutme: '关于我'

# friends:
#   友情链接1: http://localhost:4000/
#   友情链接2: http://localhost:4000/
#   友情链接3: http://localhost:4000/
#   友情链接4: http://localhost:4000/
#   友情链接5: http://localhost:4000/
#   友情链接6: http://localhost:4000/

aboutme: <span>卖马为生！</span>
