# Header
menu:
  主页: /
  所有文章: /archives
  随笔: /tag/随笔/
  关于我: /aboutme

# SubNav
subnav:
  github: "https://ithack.github.io"
  weibo: "http://weibo.com/271855993?is_all=1"
  rss: "#"
  zhihu: "https://www.zhihu.com/people/yy-yy-98"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: 

#你的头像url
avatar: "http://oap59rfi2.bkt.clouddn.com/QQ%E5%9B%BE%E7%89%8720160722111113.jpg"
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: github
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
#friends:
  #奥巴马的博客: http://localhost:4000/
  #卡卡的美丽传说: http://localhost:4000/
  #本泽马的博客: http://localhost:4000/
  #吉格斯的博客: http://localhost:4000/
  #习大大大不同: http://localhost:4000/
  #w托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 从事前端工作四年，喜欢挑战刺激项目！
